[[XPA]]
arch = "aarch64"
git-tree-sha1 = "bff9bc6d6d76be3aea888e6c653b6e2d313f969e"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "0602d90fca2fba28a19ade45b7ac9e3ce967fe6e861440b24877c560c7cf3a49"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.aarch64-linux-musl.tar.gz"
[[XPA]]
arch = "i686"
git-tree-sha1 = "89b5134899164986649df3e4aee3c37dd7c33700"
os = "windows"

    [[XPA.download]]
    sha256 = "ca2bfc61527d904599b7e61f6a5557d0ecd980b32b9078ee967f1515793317fe"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.i686-w64-mingw32.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "81e33dea07023bf4e672e3987af4f03664e5d758"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "b83963fb09c8b5b99516993543fe8e84274b90be68430b2bbb1a9999a17e3302"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.x86_64-linux-musl.tar.gz"
[[XPA]]
arch = "i686"
git-tree-sha1 = "01804c8baf2420db24891073e71b3efacd499f03"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "fd382f12bab4231880ec2734c3fc5c5b3b4a3c4f700dde5829dfc2d300f32baf"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.i686-linux-gnu.tar.gz"
[[XPA]]
arch = "armv7l"
git-tree-sha1 = "1adb3f1525d16c78090993f79148ac08c1c5383f"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "e629f8b93b219d6d0b1044444903e161ffeae5e3040c189b0846422dc59cbc2b"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.armv7l-linux-gnueabihf.tar.gz"
[[XPA]]
arch = "aarch64"
git-tree-sha1 = "8b73254ac0759e280b297fc55fcca7712124ea07"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "8d4541fa55a48b5859e80229f7fa849a516fc4a3bcdaf024e20e22d1766773f4"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.aarch64-linux-gnu.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "5b112f914e2a2841a6c6f0252d191208462cb0c8"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "8c6b2bb5e81b73bcc31c467bcd7694a9c99213eb93d241445f4a862ee1745c66"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.x86_64-linux-gnu.tar.gz"
[[XPA]]
arch = "powerpc64le"
git-tree-sha1 = "239331a415ed74e518b006fab47d37ad4de5f88c"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "a603387ded5d156d84439ce9410d5ffaf2a5bbfc6947110a2f88c9fe0d5b80c6"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.powerpc64le-linux-gnu.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "96da53a1786a603ff063680ebe9fb215b258a392"
os = "macos"

    [[XPA.download]]
    sha256 = "64734d071edd87f8202989e7ca8faadcabc60eb67568b2770ae9d3baaa094de3"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.x86_64-apple-darwin14.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "60618eb983aca7a5e8266915891c9c435eb900ae"
os = "freebsd"

    [[XPA.download]]
    sha256 = "e94f5f53cea9ccb3556e2c51a26bccb2ee14d738bd4d0c5ec1d8b7071af84e54"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.x86_64-unknown-freebsd11.1.tar.gz"
[[XPA]]
arch = "i686"
git-tree-sha1 = "d436e0bb78103ea5fd51f58e449eae2e0b9e30f1"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "19ca952257b8c5b7836927c9ceb061df4bc95589c03df4084eb432bf6b99687a"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.i686-linux-musl.tar.gz"
[[XPA]]
arch = "armv7l"
git-tree-sha1 = "e48f2db5b8637dbcb304c7264f0e79dfec9b2b33"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "3d3a74942c8cb99b9f7c56dee83449c489af35bd044aeeb9ff08d3a7a97f5ee9"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.armv7l-linux-musleabihf.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "00a67b5c429eec637db3d39756e2222c6ca064e0"
os = "windows"

    [[XPA.download]]
    sha256 = "c78d7f45f37c88bafd20248b0777004c5fa20e90bbc6a1d1c7731ba10147d43c"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.19+0/XPA.v2.1.19.x86_64-w64-mingw32.tar.gz"
