[[XPA]]
arch = "aarch64"
git-tree-sha1 = "b0ec177c1c8b5f42deea20ca8eb8e5c365ddf548"
os = "macos"

    [[XPA.download]]
    sha256 = "ccf4712ded51dfe31a5a62c6fab358b544b001b98378dfbd4bba2585e9bd0866"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.aarch64-apple-darwin.tar.gz"
[[XPA]]
arch = "aarch64"
git-tree-sha1 = "c46c6aa8dfe9c7f5b552a8d0f7bd2ba68c9974f1"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "5e3c34f0c38c5e1f00d5636d8c7afabf1c106d1e6df39f2a1b897c9f4730e6e8"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.aarch64-linux-gnu.tar.gz"
[[XPA]]
arch = "aarch64"
git-tree-sha1 = "4cf424e1b5128d768c5ca2276df3cebd90fa064b"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "a61f30c860e30d382c03151a8f8705c6596140da56a8fb189399dbbff621214d"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.aarch64-linux-musl.tar.gz"
[[XPA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "efa8b22dbfe9544bbcd297ae78342fde193f25b2"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "621a60a866b3e06aa81e7c0188c333cc5c1fe5682a8844103cf18cd6006f9b82"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.armv6l-linux-gnueabihf.tar.gz"
[[XPA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e6fee7dd104b46d1b2579da3709c57066218bbba"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "432e95ec17554dcd71cd9ba20d3eea270807a90d0f0497f688d95f9015726ac2"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.armv6l-linux-musleabihf.tar.gz"
[[XPA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9aa074a82b5d4fa3d5ee87c57642b1bab2f380a"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "ed42242452908bcaded6f68968f66aac3839c0d51d19a55449bbb5898190dae4"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.armv7l-linux-gnueabihf.tar.gz"
[[XPA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4b4043831b2d395fc24cd0a92da29c2a7c09770"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "826ecb405fe341689290ec2609a6ff2e6977a5f886cdf3ceb1242c26f56325fd"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.armv7l-linux-musleabihf.tar.gz"
[[XPA]]
arch = "i686"
git-tree-sha1 = "778417241585fbf49caf9229be8b3ccb8156fbab"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "38038d69c66c9dc09ded903bce4e39d317ac1d8cc33bea09cc629da510c2d3da"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.i686-linux-gnu.tar.gz"
[[XPA]]
arch = "i686"
git-tree-sha1 = "0f444c065f27bac2ebf627d7ddf5dc1a6435186a"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "1fdafdedc1772aefacd35337a916336e8c49b06cfa39ac5b02de843a63bcdee2"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.i686-linux-musl.tar.gz"
[[XPA]]
arch = "i686"
git-tree-sha1 = "74549501f47b126c2c29e9d042fd5bb14804deae"
os = "windows"

    [[XPA.download]]
    sha256 = "10c16319ec66855f4eb66bb59d1163266d86d6ac0646d8330acb0133b4743ecb"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.i686-w64-mingw32.tar.gz"
[[XPA]]
arch = "powerpc64le"
git-tree-sha1 = "66793648e76eca7b55fe30530e874bf1f57c9db7"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "04fba69684cf61a92f305655cc96624d358bba618c078bb7a15b4e1bdadef91c"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.powerpc64le-linux-gnu.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "f5f227a0ff7f5250f691e3f778beed9b620c6394"
os = "macos"

    [[XPA.download]]
    sha256 = "e131d526a56d60fb776d140be1eaeae0a2528d7e7dc06dcf3fbd58589f77e7c7"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.x86_64-apple-darwin.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "7adad808755353464bb65439e43b0cf984db0a73"
libc = "glibc"
os = "linux"

    [[XPA.download]]
    sha256 = "3aaa144e3ff08fcf90a849d3c9234cf75b11e7fae0d5b40ac7a00b760bc34bda"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.x86_64-linux-gnu.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "424eb9a8076d459598d5c39f310bbaff33ae17b2"
libc = "musl"
os = "linux"

    [[XPA.download]]
    sha256 = "98fab48bfaf45b9fb6417fd58014142b5bc24bc1dee45de6f03f6464b3410e59"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.x86_64-linux-musl.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "ce0e4d9b39ddec1d8f8c08005c2610ee845cb436"
os = "freebsd"

    [[XPA.download]]
    sha256 = "9b08fb35428a82349583ce70f4d840382e2661563100c551d97948771289e700"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.x86_64-unknown-freebsd.tar.gz"
[[XPA]]
arch = "x86_64"
git-tree-sha1 = "03f8563cdd1b142ce6e537b2c6ed9f3d79c35b79"
os = "windows"

    [[XPA.download]]
    sha256 = "ffb519ea9a6a841780bbd395000f57a8f4ceb1f5ec2538f7700e0443ed84216f"
    url = "https://github.com/JuliaBinaryWrappers/XPA_jll.jl/releases/download/XPA-v2.1.21+0/XPA.v2.1.21.x86_64-w64-mingw32.tar.gz"
